<?php
fwrite($file, "<?php\n");
fwrite($file, "/**\n");
fwrite($file, " * File generated with MySimpleORM v$msorm_version\n");
fwrite($file, " *\n");
fwrite($file, " * You should not modify this file.\n");
fwrite($file, " * If you need to add or modify some functionalities offered by this file,\n");
fwrite($file, " * you should see and modify the child class corresponding to this file.\n");
fwrite($file, " */\n");
fwrite($file, "\n");
fwrite($file, "namespace $nsp"."core;\n");
fwrite($file, "\n");
fwrite($file, "use \\$nsp"."exceptions\\RawDatasManagerException;\n");
fwrite($file, "\n");
fwrite($file, "/**\n");
fwrite($file, " * @class RawDatasManagerCore : a class for managing datas in the database.\n");
fwrite($file, " * Unlike all other Core manager classes this manager doesn't deal with objects but only with datas of any table of the schema as described\n");
fwrite($file, " * in the xml file used for project generation, including crossref tables.\n");
fwrite($file, " * This could already be done in any other manager of the project, but for clarity reasons, it's better to use this manager any time you \n");
fwrite($file, " * have to do specific query's implying multiple tables (data maintenance, weird things, raw datas extractions ...)\n");
fwrite($file, " * Like all other CoreManager classes, the class is a singleton an should not be instanciate.\n");
fwrite($file, " * The right way to deal with this class is to call the getInstance method on the subclass RawDatasManager\n");
fwrite($file, " * Ex :\n");
fwrite($file, " * \$manager = RawDatasManager::getInstance();\n");
fwrite($file, " * \$datas = \$manager->select('tablename',array('columname', 'value'));\n");
fwrite($file, " * ...\n");
fwrite($file, " */\n");
fwrite($file, "class RawDatasManagerCore {\n");
fwrite($file, "	\n");
fwrite($file, "	// Class attributes for object management\n");
fwrite($file, "	protected \$db;\n");
fwrite($file, "	protected static \$instance;\n");
fwrite($file, "\n");
fwrite($file, "	protected static \$tables = array(");
$first = true;
foreach(array_keys($raw_db_model) as $tablename){
if(! $first){
fwrite($file, ", ");
}
fwrite($file, "'$tablename'");
$first = false;
}
fwrite($file, ");\n");
fwrite($file, "	protected static \$columns = array(\n");
$first = true;
foreach($raw_db_model as $tablename => $datas){
if(! $first){
fwrite($file, ", \n");
}
fwrite($file, "		'$tablename' => array(");
$first_column = true;
foreach(array_keys($datas['columns']) as $column_name){
if(! $first_column){
fwrite($file, ", ");
}
fwrite($file, "'$column_name'");
$first_column = false;
}
fwrite($file, ")");
$first = false;
}
fwrite($file, "\n");
fwrite($file, "	);\n");
fwrite($file, "	\n");
fwrite($file, "	protected \$stmts = array();\n");
fwrite($file, "	\n");
fwrite($file, "	protected const OPERATORS = array(\n");
fwrite($file, "		'>' => array(\n");
fwrite($file, "			'format' => '> ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'>=' => array(\n");
fwrite($file, "			'format' => '>= ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'<' => array(\n");
fwrite($file, "			'format' => '< ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'<=' => array(\n");
fwrite($file, "			'format' => '<= ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'!=' => array(\n");
fwrite($file, "			'format' => '!= ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'LIKE' => array(\n");
fwrite($file, "			'format' => 'LIKE ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'NOT LIKE' => array(\n");
fwrite($file, "			'format' => 'NOT LIKE ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'IN' => array(\n");
fwrite($file, "			'format' => 'IN (%s)',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'NOT IN' => array(\n");
fwrite($file, "			'format' => 'NOT IN (%s)',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'BETWEEN' => array(\n");
fwrite($file, "			'format' => 'BETWEEN ? AND ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'NOT BETWEEN' => array(\n");
fwrite($file, "			'format' => 'NOT BETWEEN ? AND ?',\n");
fwrite($file, "			'parametrized' => true\n");
fwrite($file, "		),\n");
fwrite($file, "		'IS NULL' => array(\n");
fwrite($file, "			'format' => 'IS NULL',\n");
fwrite($file, "			'parametrized' => false\n");
fwrite($file, "		),\n");
fwrite($file, "		'IS NOT NULL' => array(\n");
fwrite($file, "			'format' => 'IS NOT NULL',\n");
fwrite($file, "			'parametrized' => false\n");
fwrite($file, "		)\n");
fwrite($file, "	);\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Constructor\n");
fwrite($file, "	 * This constructor should not be used.\n");
fwrite($file, "	 * Use getInstance method instead.\n");
fwrite($file, "	 * @see getInstance()\n");
fwrite($file, "	 */\n");
fwrite($file, "	protected function __construct(){\n");
fwrite($file, "		\$this->db = DatabaseConnectionProvider::getInstance();\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Use this method to get the instance of the manager\n");
fwrite($file, "	 * @return \\$nsp"."RawDatasManager\n");
fwrite($file, "	 */\n");
fwrite($file, "	public static function getInstance(){\n");
fwrite($file, "		if(! isset(static::\$instance)) {\n");
fwrite($file, "			static::\$instance = new static;\n");
fwrite($file, "		}\n");
fwrite($file, "		return static::\$instance;\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * @param string \$query an sql query with '?' if parametrized\n");
fwrite($file, "	 * @param array \$params values of query parameters. The number of elements should match the number of '?' in the query\n");
fwrite($file, "	 *\n");
fwrite($file, "	 * @return mixed if query is an sql SELECT query returns an associated array of all the rows in the result. If not, returns the result of PDO::execute method\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function query(\$query, \$params = array()) {\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$md5 = md5(\$query);\n");
fwrite($file, "			if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "				\$this->stmts[\$md5] = \$this->db->prepare(\$query);\n");
fwrite($file, "			}\n");
fwrite($file, "			\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "			\n");
fwrite($file, "			if (empty(\$params))	{\n");
fwrite($file, "				\$result = \$stmt->execute();\n");
fwrite($file, "			}\n");
fwrite($file, "			else {\n");
fwrite($file, "				\$result = \$stmt->execute(\$params);\n");
fwrite($file, "			}\n");
fwrite($file, "			if (strpos(\$query, 'SELECT') !== false) {\n");
fwrite($file, "				return \$result->fetchAll(\PDO::FETCH_ASSOC);\n");
fwrite($file, "			}\n");
fwrite($file, "			return \$result;\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\Exception \$e){\n");
fwrite($file, "			throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * \n");
fwrite($file, "	 * @param string \$table the table name on which we want to retrieve datas\n");
fwrite($file, "	 * @param array \$where an associative array which define condition for datas to be retrieved\n");
fwrite($file, "	 * Ex :\n");
fwrite($file, "	 *	array('column_name1' => \$value1, 'column_name2' => \$value2) // assume operator is 'equals'\n");
fwrite($file, "	 *  array('column_name1' => array('>', \$value1))\n");
fwrite($file, "	 * @param integer \$offset optional\n");
fwrite($file, "	 * @param integer \$limit optional\n");
fwrite($file, "	 * @param array \$order optional. If not an associative array, assume all values in the array are column names and order is ASC. Else, keys are column names and values are order (ASC or DESC)\n");
fwrite($file, "	 * Ex :\n");
fwrite($file, "	 *	array('column_name1', 'column_name2') // assume order is ASC\n");
fwrite($file, "	 *  array('column_name1' => 'DESC', 'column_name2' => 'ASC')\n");
fwrite($file, "	 * @param string \$fields the columns of table to retrieve. default is '*'\n");
fwrite($file, "	 * @return array an associative array according the query\n");
fwrite($file, "	 * @throws RawDatasManagerException\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function select(\$table, \$where = array(), \$offset = null, \$limit = null, \$order = null, \$fields = '*') {\n");
fwrite($file, "		if(in_array(\$table, self::\$tables)){\n");
fwrite($file, "			try {\n");
fwrite($file, "				if (is_array(\$fields)) {\n");
fwrite($file, "					\$selectfields = array();\n");
fwrite($file, "					foreach (\$fields as \$field) {\n");
fwrite($file, "						if(!in_array(\$field, self::\$columns[\$table])){\n");
fwrite($file, "							throw new RawDatasManagerException(\"Column \$field is not part of the \$table table\", 1);\n");
fwrite($file, "						}\n");
fwrite($file, "						\$selectfields[] = \"`\$field`\";\n");
fwrite($file, "					}\n");
fwrite($file, "					\$fieldList = implode(', ', \$selectfields);\n");
fwrite($file, "				}\n");
fwrite($file, "				else {\n");
fwrite($file, "					\$fieldList = '*';\n");
fwrite($file, "				}\n");
fwrite($file, "				\$sqlWhere = \"\";\n");
fwrite($file, "				\$sqlLimit = \"\";\n");
fwrite($file, "				\$sqlOrder = \"\";\n");
fwrite($file, "				\$values = array();\n");
fwrite($file, "				if(is_array(\$where) && !empty(\$where)){\n");
fwrite($file, "					list(\$sqlWhere, \$values) = \$this->processWhere(\$where);\n");
fwrite($file, "				}\n");
fwrite($file, "				if(! (\$offset == null && \$limit == null)){\n");
fwrite($file, "					if(\$offset >=0 && \$limit >= 0) {\n");
fwrite($file, "						\$sqlLimit = ' LIMIT :offset, :limit';\n");
fwrite($file, "						\$values[] = \$offset;\n");
fwrite($file, "						\$values[] = \$limit;\n");
fwrite($file, "					}\n");
fwrite($file, "					else{\n");
fwrite($file, "						throw new RawDatasManagerException(\"offset and limit cannot be negative values\", 1);\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				if(isset(\$order)){\n");
fwrite($file, "					\$sqlOrder = \$this->processOrder(\$order, \$table);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$sql = \"SELECT \$fieldList FROM `\$table`\".\$sqlWhere.\$sqlLimit.\$sqlOrder;\n");
fwrite($file, "				\n");
fwrite($file, "				\$md5 = md5(\$sql);\n");
fwrite($file, "				if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "					\$this->stmts[\$md5] = \$this->db->prepare(\$sql);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "				\$this->bindValues(\$stmt, \$values);\n");
fwrite($file, "				\$stmt->execute();\n");
fwrite($file, "				\n");
fwrite($file, "				return \$stmt->fetchAll(\PDO::FETCH_ASSOC);\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(RawDatasManagerException \$rdme) {\n");
fwrite($file, "				throw \$rdme;\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(\Exception \$e) {\n");
fwrite($file, "				throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		else{\n");
fwrite($file, "			throw new RawDatasManagerException(\"Table \$table is not part of the model\", 1);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * \n");
fwrite($file, "	 * @param string \$table the table name on which we want to insert datas\n");
fwrite($file, "	 * @param array \$record an associative array containing values to insert\n");
fwrite($file, "	 * Ex :\n");
fwrite($file, "	 *  array('column_name1' => 'value_1', 'column_name2' => 'value_2')\n");
fwrite($file, "	 * @throws RawDatasManagerException\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function insert(\$table, \$record) {\n");
fwrite($file, "		if(in_array(\$table, self::\$tables)){\n");
fwrite($file, "			try {\n");
fwrite($file, "				\$sql = \"INSERT INTO `\$table`\";\n");
fwrite($file, "				\$fields = array();\n");
fwrite($file, "				\$values = array();\n");
fwrite($file, "				\$stmt_vars = array();\n");
fwrite($file, "				foreach (\$record as \$field => \$value) {\n");
fwrite($file, "					if(in_array(\$field, self::\$columns[\$table])){\n");
fwrite($file, "						\$fields[] = \"`\$field`\";\n");
fwrite($file, "						\$stmt_vars[] = '?';\n");
fwrite($file, "						\$values[] = \$value;\n");
fwrite($file, "					}\n");
fwrite($file, "					else{\n");
fwrite($file, "						throw new RawDatasManagerException(\"Column \$field is not part of the \$table table\", 1);\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				\$sql .= \" (\".implode(', ', \$fields).\") VALUES (\".implode(', ', \$stmt_vars).\")\";\n");
fwrite($file, "				\$md5 = md5(\$sql);\n");
fwrite($file, "				if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "					\$this->stmts[\$md5] = \$this->db->prepare(\$sql);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "				\$this->bindValues(\$stmt, \$values);\n");
fwrite($file, "				\$stmt->execute();\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(RawDatasManagerException \$rdme) {\n");
fwrite($file, "				throw \$rdme;\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(\Exception \$e) {\n");
fwrite($file, "				throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		else{\n");
fwrite($file, "			throw new RawDatasManagerException(\"Table \$table is not part of the model\", 1);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * \n");
fwrite($file, "	 * @param string \$table the table name on which we want to insert datas\n");
fwrite($file, "	 * @param array \$fields an array containing the column names on wich we are going to give the values\n");
fwrite($file, "	 * Ex :\n");
fwrite($file, "	 *  array('column_name1', 'column_name2')\n");
fwrite($file, "	 * @param array \$sets an array of arrays containing values of each sets we want to insert\n");
fwrite($file, "	 *  array(array('value_11', 'value_12'), array('value_21', 'value_22'), array('value_31', 'value_32'))\n");
fwrite($file, "	 * @throws RawDatasManagerException\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function insertMultiple(\$table, \$fields, \$sets) {\n");
fwrite($file, "		if(in_array(\$table, self::\$tables)){\n");
fwrite($file, "			try {\n");
fwrite($file, "				\$sql = \"INSERT INTO `\$table`\";\n");
fwrite($file, "				\$sql_fields = array();\n");
fwrite($file, "				\$stmt_vars = array();\n");
fwrite($file, "				foreach (\$fields as \$field) {\n");
fwrite($file, "					if(in_array(\$field, self::\$columns[\$table])){\n");
fwrite($file, "						\$sql_fields[] = \"`\$field`\";\n");
fwrite($file, "						\$stmt_vars[] = '?';\n");
fwrite($file, "					}\n");
fwrite($file, "					else{\n");
fwrite($file, "						throw new RawDatasManagerException(\"Column \$field is not part of the \$table table\", 1);\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				\$sql .= \" (\".implode(', ', \$sql_fields).\") VALUES (\".implode(', ', \$stmt_vars).\")\";\n");
fwrite($file, "				\$md5 = md5(\$sql);\n");
fwrite($file, "				if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "					\$this->stmts[\$md5] = \$this->db->prepare(\$sql);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "				\$this->db->beginTransaction();\n");
fwrite($file, "				foreach(\$sets as \$values){\n");
fwrite($file, "					if(count(\$values) != count(\$fields)){\n");
fwrite($file, "						throw new RawDatasManagerException(\"Set has not the right number of values\", 1);\n");
fwrite($file, "					}\n");
fwrite($file, "					\$this->bindValues(\$stmt, \$values);\n");
fwrite($file, "					\$stmt->execute();\n");
fwrite($file, "				}\n");
fwrite($file, "				\$this->db->commit();\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(RawDatasManagerException \$rdme) {\n");
fwrite($file, "				throw \$rdme;\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(\Exception \$e) {\n");
fwrite($file, "				\$this->db->rollBack();\n");
fwrite($file, "				throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		else{\n");
fwrite($file, "			throw new RawDatasManagerException(\"Table \$table is not part of the model\", 1);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * \n");
fwrite($file, "	 * @param string \$table the table name on which we want to update datas\n");
fwrite($file, "	 * @param array \$record an associative array containing values to updated\n");
fwrite($file, "	 * Ex :\n");
fwrite($file, "	 *  array('column_name1' => 'value_1', 'column_name2' => 'value_2')\n");
fwrite($file, "	 * @param array \$where an associative array which define condition for datas to be update\n");
fwrite($file, "	 * Ex :\n");
fwrite($file, "	 *	array('column_name1' => \$value1, 'column_name2' => \$value2) // assume operator is 'equals'\n");
fwrite($file, "	 *  array('column_name1' => array('>', \$value1))\n");
fwrite($file, "	 * @throws RawDatasManagerException\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function update(\$table, \$record, \$where = array()) {\n");
fwrite($file, "		if(in_array(\$table, self::\$tables)){\n");
fwrite($file, "			try {\n");
fwrite($file, "				\$sql = \"UPDATE `\$table` SET \";\n");
fwrite($file, "				\$sql_fields_stmt = array();\n");
fwrite($file, "				\$values = array();\n");
fwrite($file, "				foreach (\$record as \$field => \$value) {\n");
fwrite($file, "					if(in_array(\$field, self::\$columns[\$table])){\n");
fwrite($file, "						\$sql_fields_stmt[] = \"`\$field`=?\";\n");
fwrite($file, "						\$values[] = \$value;\n");
fwrite($file, "					}\n");
fwrite($file, "					else{\n");
fwrite($file, "						throw new RawDatasManagerException(\"Column \$field is not part of the \$table table\", 1);\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				\$sql .= implode(', ', \$sql_fields_stmt);\n");
fwrite($file, "				\$sqlWhere = \"\";\n");
fwrite($file, "				if(is_array(\$where) && !empty(\$where)){\n");
fwrite($file, "					list(\$sqlWhere, \$whereValues) = \$this->processWhere(\$where);\n");
fwrite($file, "					foreach(\$whereValues as \$val){\n");
fwrite($file, "						\$values[] = \$val;\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				\$sql .= \$sqlWhere;\n");
fwrite($file, "				\$md5 = md5(\$sql);\n");
fwrite($file, "				if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "					\$this->stmts[\$md5] = \$this->db->prepare(\$sql);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "				\$this->bindValues(\$stmt, \$values);\n");
fwrite($file, "				\$stmt->execute();\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(RawDatasManagerException \$rdme) {\n");
fwrite($file, "				throw \$rdme;\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(\Exception \$e) {\n");
fwrite($file, "				throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		else{\n");
fwrite($file, "			throw new RawDatasManagerException(\"Table \$table is not part of the model\", 1);\n");
fwrite($file, "		}	\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * \n");
fwrite($file, "	 * @param string \$table the table name on which we want to delete datas\n");
fwrite($file, "	 * @param array \$where an associative array which define condition for datas to be deleted\n");
fwrite($file, "	 * Ex :\n");
fwrite($file, "	 *	array('column_name1' => \$value1, 'column_name2' => \$value2) // assume operator is 'equals'\n");
fwrite($file, "	 *  array('column_name1' => array('>', \$value1))\n");
fwrite($file, "	 * @throws RawDatasManagerException\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function delete(\$table, \$where) {\n");
fwrite($file, "		if(in_array(\$table, self::\$tables)){\n");
fwrite($file, "			try {\n");
fwrite($file, "				\$sql = \"DELETE FROM `\$table`\";\n");
fwrite($file, "				\$sqlWhere = \"\";\n");
fwrite($file, "				if(is_array(\$where) && !empty(\$where)){\n");
fwrite($file, "					list(\$sqlWhere, \$whereValues) = \$this->processWhere(\$where);\n");
fwrite($file, "					foreach(\$whereValues as \$val){\n");
fwrite($file, "						\$values[] = \$val;\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				else{\n");
fwrite($file, "					throw new RawDatasManagerException(\"WHERE clause in delete method have to be set. if you want to clean a table, use truncate method instead\", 1);\n");
fwrite($file, "				}\n");
fwrite($file, "				if(\$sqlWhere == \"\"){\n");
fwrite($file, "					throw new RawDatasManagerException(\"Computing WHERE clause from \\\$where parameter returned an empty string, use truncate method instead\", 1);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$sql .= \$sqlWhere;\n");
fwrite($file, "				\$md5 = md5(\$sql);\n");
fwrite($file, "				if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "					\$this->stmts[\$md5] = \$this->db->prepare(\$sql);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "				\$this->bindValues(\$stmt, \$values);\n");
fwrite($file, "				\$stmt->execute();\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(RawDatasManagerException \$rdme) {\n");
fwrite($file, "				throw \$rdme;\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(\Exception \$e) {\n");
fwrite($file, "				throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		else{\n");
fwrite($file, "			throw new RawDatasManagerException(\"Table \$table is not part of the model\", 1);\n");
fwrite($file, "		}	\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "	\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * \n");
fwrite($file, "	 * @param string \$table the table name on which we want to count the number of rows\n");
fwrite($file, "	 * @return integer the number of rows in the table\n");
fwrite($file, "	 * @throws RawDatasManagerException\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function count(\$table) {\n");
fwrite($file, "		if(in_array(\$table, self::\$tables)){\n");
fwrite($file, "			try {\n");
fwrite($file, "				\$sql = \"SELECT count(*) FROM `\$table`\";\n");
fwrite($file, "				\$md5 = md5(\$sql);\n");
fwrite($file, "				if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "					\$this->stmts[\$md5] = \$this->db->prepare(\$sql);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "				\$stmt->execute();\n");
fwrite($file, "				\n");
fwrite($file, "				\$datas = \$stmt->fetch(\PDO::FETCH_NUM);\n");
fwrite($file, "				return \$datas[0];\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(\Exception \$e) {\n");
fwrite($file, "				throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		else{\n");
fwrite($file, "			throw new RawDatasManagerException(\"Table \$table is not part of the model\", 1);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * \n");
fwrite($file, "	 * @param string \$table the table name we want to delete datas\n");
fwrite($file, "	 * @throws RawDatasManagerException\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function truncate(\$table) {\n");
fwrite($file, "		if(in_array(\$table, self::\$tables)){\n");
fwrite($file, "			try {\n");
fwrite($file, "				\$sql = \"TRUNCATE TABLE `\$table`\";\$md5 = md5(\$sql);\n");
fwrite($file, "				if(!isset(\$this->stmts[\$md5])){\n");
fwrite($file, "					\$this->stmts[\$md5] = \$this->db->prepare(\$sql);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$stmt = \$this->stmts[\$md5];\n");
fwrite($file, "				\$stmt->execute();\n");
fwrite($file, "			}\n");
fwrite($file, "			catch (\Exception \$e) {\n");
fwrite($file, "				throw new RawDatasManagerException(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		else{\n");
fwrite($file, "			throw new RawDatasManagerException(\"Table \$table is not part of the model\", 1);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "\n");
fwrite($file, "	\n");
fwrite($file, "	protected function processWhere(\$where) {\n");
fwrite($file, "		\$conditions = array();\n");
fwrite($file, "		\$values = array();\n");
fwrite($file, "		foreach (\$where as \$field => \$condition) {\n");
fwrite($file, "			list(\$sql, \$vals) = \$this->getCondition(\$field, \$condition);\n");
fwrite($file, "			\$conditions[] = \$sql;\n");
fwrite($file, "			if(isset(\$vals)){\n");
fwrite($file, "				if(is_array(\$vals)){\n");
fwrite($file, "					foreach(\$vals as \$val){\n");
fwrite($file, "						\$values[] = \$val;\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				else{\n");
fwrite($file, "					\$values[] = \$vals;\n");
fwrite($file, "				}\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		return array(\" WHERE \".implode(' AND ', \$conditions), \$values);\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "\n");
fwrite($file, "	protected function getCondition(\$field, \$condition) {\n");
fwrite($file, "		//echo print_r(\$condition,true);\n");
fwrite($file, "		if(is_array(\$condition)) { // operator, value(s)\n");
fwrite($file, "			\$values = array();\n");
fwrite($file, "			\$keys = array();\n");
fwrite($file, "			\$operator = \$condition[0];\n");
fwrite($file, "			if(! is_array(\$condition[1])){\n");
fwrite($file, "				\$values[] = \$condition[1];\n");
fwrite($file, "			}\n");
fwrite($file, "			else {\n");
fwrite($file, "				foreach(\$condition[1] as \$val) {\n");
fwrite($file, "					\$values[] = \$val;\n");
fwrite($file, "					\$keys[] = \"?\";\n");
fwrite($file, "				}\n");
fwrite($file, "			}\n");
fwrite($file, "			return array(\"`\$field` \".sprintf(self::OPERATORS[strtoupper(\$operator)]['format'], implode(', ', \$keys)), \$values);\n");
fwrite($file, "		}\n");
fwrite($file, "		elseif(isset(self::OPERATORS[strtoupper(\$condition)]) && (! self::OPERATORS[strtoupper(\$condition)]['parametrized'])){\n");
fwrite($file, "			return array(\"`\$field` \".self::OPERATORS[strtoupper(\$condition)]['format'], null);\n");
fwrite($file, "		}\n");
fwrite($file, "		return array(\"`\$field` = ?\", \$condition);\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "	protected function processOrder(\$sortAttributes, \$table) {\n");
fwrite($file, "		\$order_string = \"\";\n");
fwrite($file, "		if(is_array(\$sortAttributes)){\n");
fwrite($file, "			\$order_string_tab = array();\n");
fwrite($file, "			if(array_values(\$sortAttributes) === \$sortAttributes){	//it's not an associative array (just column names as values), assume order is ASC\n");
fwrite($file, "				foreach(\$sortAttributes as \$attr){\n");
fwrite($file, "					if(in_array(\$attr, self::\$columns[\$table])){\n");
fwrite($file, "						\$order_string_tab[] = \"`\$attr`\";\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "			}\n");
fwrite($file, "			else{\n");
fwrite($file, "				foreach(\$sortAttributes as \$attr => \$order){\n");
fwrite($file, "					if(in_array(\$attr, self::\$columns[\$table]) && (\$order == 'ASC' || \$order == 'DESC')){\n");
fwrite($file, "						\$order_string_tab[] = \"`\$attr` \$order\";\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "			}\n");
fwrite($file, "			if(! empty(\$order_string_tab)){\n");
fwrite($file, "				\$order_string = ' ORDER BY '.implode(', ', \$order_string_tab);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "		elseif(in_array(\$sortAttributes, self::\$columns[\$table])){\n");
fwrite($file, "			\$order_string = \" ORDER BY `\$sortAttributes`\";\n");
fwrite($file, "		}\n");
fwrite($file, "		return \$order_string;\n");
fwrite($file, "	}\n");
fwrite($file, "	\n");
fwrite($file, "	\n");
fwrite($file, "	protected function bindValues(\$statement, \$values) {\n");
fwrite($file, "		if(is_array(\$values)) {\n");
fwrite($file, "			foreach(\$values as \$i => \$value) {\n");
fwrite($file, "				if(is_integer(\$value) || (is_numeric(\$value) && (strval(\$value) === strval(intval(\$value))))) {\n");
fwrite($file, "					\$type = \PDO::PARAM_INT;\n");
fwrite($file, "					\$value = intval(\$value);\n");
fwrite($file, "				}\n");
fwrite($file, "				elseif(is_null(\$value) || \$value === 'NULL') {\n");
fwrite($file, "					\$type = \PDO::PARAM_NULL;\n");
fwrite($file, "					\$value = null;\n");
fwrite($file, "				}\n");
fwrite($file, "				elseif(is_bool(\$value)) {\n");
fwrite($file, "					\$type = \PDO::PARAM_BOOL;\n");
fwrite($file, "				}\n");
fwrite($file, "				else{\n");
fwrite($file, "					\$type = \PDO::PARAM_STR;\n");
fwrite($file, "				}\n");
fwrite($file, "				\$statement->bindValue(intval(\$i + 1), \$value, \$type);\n");
fwrite($file, "			}\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "}\n");
fwrite($file, "?>");
?>